import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    // Sidebar
    partner: "PARTNER",
    principal: "MAIN",
    overview: "Overview",
    localMissions: "My Local Missions",
    collectionPoints: "My Collection Points",
    notifications: "Alerts & Notifications",
    settings: "Organization Profile",
    logout: "Logout",
    
    // Common UI
    searchPlaceholder: "Search...",
    sortBy: "SORT BY:",
    dateLabel: "DATE",
    createdDate: "CREATED DATE",
    statusLabel: "STATUS",
    actionsLabel: "ACTIONS",
    previous: "Previous",
    next: "Next",
    showing: "Showing",
    to: "to",
    of: "of",
    results: "results",
    allStatuses: "All statuses",
    dateDesc: "Date (Newest)",
    dateAsc: "Date (Oldest)",
    nameAsc: "Name (A-Z)",
    nameDesc: "Name (Z-A)",
    noItemsFound: "No items found.",
    noMissionsFound: "No missions found.",
    titleLabel: "Title",
    descriptionLabel: "Description",
    missionPhoto: "Mission Photo",
    editMissionTitle: "Edit Mission",
    createMissionTitle: "Create Mission",
    deleteMissionTitle: "Delete Mission",
    confirmDeleteMission: "Are you sure you want to delete this mission?",
    participants: "Participants",
    durationLabel: "Duration",
    closeBtn: "Close",
    sendingLabel: "Sending...",
    latitudeLabel: "Latitude",
    longitudeLabel: "Longitude",
    photoLabel: "Photo",
    deletePointTitle: "Delete Collection Point",
    confirmDeletePoint: "Are you sure you want to delete this collection point?",
    addPointLabel: "Add Collection Point",
    editPointLabel: "Edit Collection Point",
    generalInfo: "General Information",
    localisationLabel: "Localization",
    discardBtn: "Discard",
    saveChanges: "Save Changes",
    createBtn: "Create",
    totalCount: "Total",
    selectOption: "Select...",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    rejected: "Rejected",
    approved: "Approved",
    
    // Login & Register
    loginTitle: "Partner Login",
    registerTitle: "Partner Registration",
    emailLabel: "Email",
    passwordLabel: "Password",
    rememberMe: "Keep me signed in",
    forgotPassword: "Forgotten password",
    signInBtn: "Sign In",
    signUpBtn: "Sign Up",
    signingIn: "Signing in...",
    signingUp: "Registering...",
    partnerOnly: "Partner access only",
    welcomeBack: "Welcome back",
    loginFailed: "Login failed. Check your credentials.",
    networkError: "Network error. Please try again.",
    enterEmail: "Enter email",
    enterPassword: "Enter password",
    fillAllFields: "Please fill in all fields.",
    
    // Settings Profile
    firstName: "Representative First Name",
    lastName: "Representative Last Name",
    phone: "Phone Number",
    company: "Company / Organization Name",
    address: "Street Address",
    cityLabel: "City",
    postalCode: "Postal Code",
    countryLabel: "Country",
    websiteLabel: "Website URL",
    bioIntro: "About Organization",
    bioPlaceholder: "Describe your organization, mission...",
    close: "Close",
    cancel: "Cancel",
    saveProfile: "Save Profile",
    saving: "Saving...",
    
    // Partner specifics
    activePointsLabel: "active collection points",
    noDescription: "No description",
    dashboardSub: "Dashboard — Hesteka Partner",
    pointsList: "List of Collection Points",
    addPoint: "Add Collection Point",
    missionsTitle: "Local Missions",
    missionsSub: "Manage your local community missions",
    allMissions: "All Local Missions",
    createMission: "Create Local Mission",
    addMission: "Add Mission",
    cancelBtn: "Cancel",
    collectionPointsTitle: "Collection Points",
    collectionPointsSub: "Manage your deposit points",
    
    // New translations for partners
    pendingApprovals: "Pending Approvals",
    myMissions: "My Missions",
    myCollectionPoints: "My Collection Points",
    participantsList: "Participants List",
    approveBtn: "Approve",
    rejectBtn: "Reject",
    statusUpdated: "Status updated successfully",
    participantApproved: "Participant approved (+points awarded)",
    participantRejected: "Participant request rejected",
    logoLabel: "Company Logo",
    bannerLabel: "Organization Banner Photo",
    generalProfile: "General Organization Profile",
    companyDetails: "Company Details",
    latitude: "Latitude",
    longitude: "Longitude",
    locationMapPicker: "Location Map Picker",
    mapInstruction: "Click on the map or drag the marker to select coordinates",
    aboutOrg: "About Organization (Description)",
    aboutOrgPlaceholder: "Describe your company (max 100 characters)",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    updatePassword: "Update Password",
    profileDetailsTab: "Profile details",
    changePasswordTab: "Change Password",
    profileUpdated: "Profile details updated successfully.",
    profileUpdateFailed: "Failed to update profile.",
    profileUpdateError: "Error updating profile details.",
    passwordsNotMatch: "Passwords do not match.",
    passwordChangedSuccess: "Password changed successfully. Please log in again.",
    passwordChangeFailed: "Failed to change password.",
    passwordChangeError: "Error updating password.",
    noCoverImage: "No Cover Image Configured",
    changeCover: "Change Cover Image",
    changeLogo: "Change Logo",
    addressNotConfigured: "Address not configured",
    editProfile: "Edit Profile",
    totalParticipants: "Total Participants",
    inProgress: "in progress",
    registeredForMissions: "registered for your missions",
    viewAll: "View All",
    noMissionsYet: "No missions created yet.",
    createNewMission: "Create New Mission",
    notificationCenter: "Notification Center",
    notificationSubtitle: "Keep up with community activity and registrations",
    markAllAsRead: "Mark all as read",
    newAlert: "New Alert",
    noNotifications: "No notifications found",
    toastLoadNotifFailed: "Failed to load notifications.",
    toastUpdateNotifFailed: "Failed to update notification status.",
    toastAllMarkedRead: "All notifications marked as read.",
    toastMarkAllFailed: "Failed to update notifications.",
    toastNotifDeleted: "Notification deleted.",
    toastDeleteNotifFailed: "Failed to delete notification.",
    activeMissionsSub: "active local missions",
    pointsManagedSub: "collection points managed",
    communityUpdatesSub: "Community updates & messages",
    configureProfileSub: "Configure company logo, banner, and profile details",
    noNotifs: "No notifications",
    pointName: "Point Name",
    coordinates: "Coordinates",
    depositMap: "Deposit Locations Map",
    noPointsYet: "No collection points configured yet.",
    searchPlaceholderPoints: "Search by name or address...",
    streetAddress: "Street Address",
    pointPhoto: "Point Location Photo",
    uploadImage: "Upload Image",
    createPoint: "Create Point",
    pointDetails: "Point Details",
    closeDetails: "Close Details",
    confirmDeletePointMsg: "Are you sure you want to delete this point? Users will no longer see it on the map.",
    upcomingLabel: "Upcoming",
    completedLabel: "Completed",
    activeLabel: "Active",
    pointsRequiredLabel: "Points Required",
    durationLabel: "Duration",
    registrationsLabel: "Participants",
    filterStatusLabel: "Filter Status",
    searchPlaceholderMissions: "Search by mission name or category...",
    emptyMissionsList: "No local missions created yet.",
    noRegistrationsYet: "No participants for this mission yet.",
    createMissionBtn: "Create Local Mission",
    editMissionBtn: "Edit Local Mission",
    deleteMissionBtn: "Delete Local Mission",
    confirmDelete: "Delete",
    titlePlaceholder: "e.g. Help Plant Urban Trees",
    categoryPlaceholder: "e.g. Planting, Cleaning",
    pointsPlaceholder: "e.g. 50",
    uploadPhoto: "Upload Photo",
    changePhoto: "Change Photo",
    pointsGrantedLabel: "Points Granted",
    analytics: "Analytics",
    supportMessages: "Support Messages",
    faq: "FAQ",
    supportProofs: "Support Proofs",
    pendingValidationDon: "Pending Validations",
    validatedThisMonth: "Validated this month",
    refused: "Refused",
    ptsGranted: "Points Granted",
    vsLastMonth: "vs last month",
    toValidate: "to validate",
    depositsThisMonth: "Deposits This Month",
    refusalReasons: "Refusal Reasons",
    categoryTrend: "Analytics",
    myDepositLocations: "My Deposit Locations",
    noActivePointSelected: "No active point selected",
    ptsRequired: "pts required",
    mission: "Mission",
    myOrganization: "My Organization",
    enter: "Enter",
    visualPreview: "Visual Preview",
    newRecord: "New Record",
    searchLocationPlaceholder: "Search location...",
    findBtn: "Find",
    mapLocation: "Map Location",
    locationDetails: "Location Details",
    clickToPin: "CLICK TO PIN",
    points: "Points Reward",
    toastMissionCreated: "Local mission created successfully.",
    toastMissionUpdated: "Local mission updated successfully.",
    toastMissionSaveFailed: "Failed to save local mission.",
    toastMissionDeleted: "Local mission deleted successfully.",
    toastMissionDeleteFailed: "Failed to delete local mission.",
    toastApproveSuccess: "Participant registration approved!",
    toastApproveFailed: "Failed to approve participant.",
    toastLoadMissionsFailed: "Failed to load missions.",
    toastLoadParticipantsFailed: "Failed to load participants list.",
    toastLoadPointsFailed: "Failed to load collection points.",
    toastPointCreated: "Collection point created successfully.",
    toastPointUpdated: "Collection point updated successfully.",
    toastPointSaveFailed: "Failed to save collection point.",
    toastPointDeleted: "Collection point deleted successfully.",
    toastPointDeleteFailed: "Failed to delete collection point.",
    approveBtn: "Approve",
    rejectBtn: "Reject",
    approved: "Approved",
    rejected: "Rejected",
    toastRejectSuccess: "Participant rejected successfully.",
    toastRejectFailed: "Failed to reject participant.",
    food: "Food",
    litter: "Litter",
    toys: "Toys",
    medicine: "Medicine",
    other: "Other",
    blurredPhoto: "Blurred Photo",
    itemNotVisible: "Item Not Visible",
    pointNotRecognized: "Point Not Recognized",
    janShort: "JAN",
    febShort: "FEB",
    marShort: "MAR",
    aprShort: "APR",
    mayShort: "MAY",
    junShort: "JUN",
    julShort: "JUL",
    augShort: "AUG",
    sepShort: "SEP",
    octShort: "OCT",
    novShort: "NOV",
    decShort: "DEC",
    sunShort: "SUN",
    monShort: "MON",
    tueShort: "TUE",
    wedShort: "WED",
    thuShort: "THU",
    friShort: "FRI",
    satShort: "SAT",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    lifetime: "Lifetime",
    noDataFound: "NO DATA FOUND.",
    exportBtn: "Export",
    hestekaPartner: "HESTEKA Partner",
    supportVia: "Support Via",
    quantityLabel: "Quantity",
    association: "Association",
    dateLabel: "DATE",
    statusLabel: "STATUS",
    actionsLabel: "ACTIONS",
    viewImage: "View Image",
    allStatuses: "ALL",
    pending: "PENDING",
    loadingLabel: "LOADING...",
    supportProofsSub: "Review and validate physical donations",
    analyticsSub: "Track your ecosystem growth",
    supportMessagesSub: "Contact our support team",
    faqSub: "Frequently asked questions",
    participationsMonth: "Participants per Month",
    missionsTitle: "Local Missions",
    collectionPointsTitle: "Collection Points",
    newParticipantTitle: "New Participant!",
    faqTitle: "Frequently Asked Questions",
    faqSubtitle: "Find answers to common questions about managing your collection points, local missions, and partner account.",
    noFaqsFound: "No FAQs found at this time.",
    nameField: "Name",
    emailField: "Email",
    newTicket: "New Support Ticket",
    subjectLabel: "SUBJECT",
    subject: "Subject",
    message: "Message",
    noMessagesFound: "YOU HAVEN'T SENT ANY SUPPORT MESSAGES YET.",
    messageSentSuccess: "Support message sent successfully! We will contact you soon.",
    messageSentFailed: "Failed to send message",
    view: "View",
    ticketDetails: "Ticket Details",
    yourMessage: "Your Message",
    adminReply: "Admin Reply",
    close: "Close",
    searchPlaceholder: "Search...",
  },
  fr: {
    // Sidebar
    partner: "PARTENAIRE",
    principal: "PRINCIPAL",
    overview: "Vue globale",
    localMissions: "Mes Missions Locales",
    collectionPoints: "Mes Points de Collecte",
    notifications: "Alertes & Notifications",
    settings: "Profil de l'Organisation",
    logout: "Déconnexion",
    
    // Common UI
    searchPlaceholder: "Rechercher...",
    sortBy: "TRIER PAR:",
    dateLabel: "DATE",
    createdDate: "DATE DE CRÉATION",
    statusLabel: "STATUT",
    actionsLabel: "ACTIONS",
    previous: "Précédent",
    next: "Suivant",
    showing: "Affichage de",
    to: "à",
    of: "sur",
    results: "résultats",
    allStatuses: "Tous les statuts",
    dateDesc: "Date (Plus récent)",
    dateAsc: "Date (Plus ancien)",
    nameAsc: "Nom (A-Z)",
    nameDesc: "Nom (Z-A)",
    noItemsFound: "Aucun élément trouvé.",
    noMissionsFound: "Aucune mission trouvée.",
    titleLabel: "Titre",
    descriptionLabel: "Description",
    missionPhoto: "Photo de la mission",
    editMissionTitle: "Modifier la mission",
    createMissionTitle: "Créer une mission",
    deleteMissionTitle: "Supprimer la mission",
    confirmDeleteMission: "Voulez-vous vraiment supprimer cette mission ?",
    participants: "Participants",
    durationLabel: "Durée",
    closeBtn: "Fermer",
    sendingLabel: "Envoi en cours...",
    latitudeLabel: "Latitude",
    longitudeLabel: "Longitude",
    photoLabel: "Photo",
    deletePointTitle: "Supprimer le point de collecte",
    confirmDeletePoint: "Voulez-vous vraiment supprimer ce point de collecte ?",
    addPointLabel: "Ajouter un point de collecte",
    editPointLabel: "Modifier le point de collecte",
    generalInfo: "Informations Générales",
    localisationLabel: "Localisation",
    discardBtn: "Annuler",
    saveChanges: "Enregistrer",
    createBtn: "Créer",
    totalCount: "Total",
    selectOption: "Sélectionner...",
    active: "Actif",
    inactive: "Inactif",
    pending: "En attente",
    rejected: "Rejeté",
    approved: "Approuvé",
    
    // Login & Register
    loginTitle: "Connexion Partenaire",
    registerTitle: "Inscription Partenaire",
    emailLabel: "E-mail",
    passwordLabel: "Mot de passe",
    rememberMe: "Rester connecté",
    forgotPassword: "Mot de passe oublié",
    signInBtn: "Se connecter",
    signUpBtn: "S'inscrire",
    signingIn: "Connexion en cours...",
    signingUp: "Inscription en cours...",
    partnerOnly: "Accès partenaire uniquement",
    welcomeBack: "Bon retour",
    loginFailed: "Échec de la connexion. Vérifiez vos identifiants.",
    networkError: "Erreur réseau. Veuillez réessayer.",
    enterEmail: "Entrez votre e-mail",
    enterPassword: "Entrez votre mot de passe",
    fillAllFields: "Veuillez remplir tous les champs.",
    
    // Settings Profile
    firstName: "Prénom du Représentant",
    lastName: "Nom du Représentant",
    phone: "Numéro de Téléphone",
    company: "Nom de l'Entreprise / Organisation",
    address: "Adresse",
    cityLabel: "Ville",
    postalCode: "Code Postal",
    countryLabel: "Pays",
    websiteLabel: "URL du Site Web",
    bioIntro: "À propos de l'Organisation",
    bioPlaceholder: "Décrivez votre organisation, mission...",
    close: "Fermer",
    cancel: "Annuler",
    saveProfile: "Enregistrer",
    saving: "Enregistrement...",
    
    // Partner specifics
    activePointsLabel: "points de collecte actifs",
    noDescription: "Aucune description",
    dashboardSub: "Tableau de bord — Hesteka Partenaire",
    pointsList: "Liste des points de collecte",
    addPoint: "Ajouter un point",
    missionsTitle: "Missions Locales",
    missionsSub: "Gérez vos missions communautaires locales",
    allMissions: "Toutes les Missions",
    createMission: "Créer une Mission",
    addMission: "Ajouter une mission",
    cancelBtn: "Annuler",
    collectionPointsTitle: "Points de Collecte",
    collectionPointsSub: "Gérez vos points de dépôt",
    
    // New translations for partners
    pendingApprovals: "Approbations en attente",
    myMissions: "Mes Missions",
    myCollectionPoints: "Mes Points de Collecte",
    participantsList: "Liste des Participants",
    approveBtn: "Valider",
    rejectBtn: "Refuser",
    statusUpdated: "Statut mis à jour avec succès",
    participantApproved: "Participant validé (+points attribués)",
    participantRejected: "Demande du participant rejetée",
    logoLabel: "Logo de l'entreprise",
    bannerLabel: "Bannière de l'organisation",
    generalProfile: "Profil Général de l'Organisation",
    companyDetails: "Détails de l'Entreprise",
    latitude: "Latitude",
    longitude: "Longitude",
    locationMapPicker: "Sélecteur de Carte de Localisation",
    mapInstruction: "Cliquez sur la carte ou glissez le marqueur pour sélectionner les coordonnées",
    aboutOrg: "À propos de l'Organisation (Description)",
    aboutOrgPlaceholder: "Décrivez votre entreprise (max 100 caractères)",
    changePassword: "Modifier le mot de passe",
    currentPassword: "Mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    confirmNewPassword: "Confirmer le nouveau mot de passe",
    updatePassword: "Mettre à jour le mot de passe",
    profileDetailsTab: "Détails du profil",
    changePasswordTab: "Modifier le mot de passe",
    profileUpdated: "Les détails du profil ont été mis à jour avec succès.",
    profileUpdateFailed: "Échec de la mise à jour du profil.",
    profileUpdateError: "Erreur lors de la mise à jour des détails du profil.",
    passwordsNotMatch: "Les mots de passe ne correspondent pas.",
    passwordChangedSuccess: "Mot de passe modifié avec succès. Veuillez vous reconnecter.",
    passwordChangeFailed: "Échec de la modification du mot de passe.",
    passwordChangeError: "Erreur lors de la mise à jour du mot de passe.",
    noCoverImage: "Aucune image de couverture configurée",
    changeCover: "Changer l'image de couverture",
    changeLogo: "Changer le logo",
    addressNotConfigured: "Adresse non configurée",
    editProfile: "Modifier le profil",
    totalParticipants: "Total des Participants",
    inProgress: "en cours",
    registeredForMissions: "inscrits à vos missions",
    viewAll: "Voir tout",
    noMissionsYet: "Aucune mission créée pour le moment.",
    createNewMission: "Créer une nouvelle mission",
    notificationCenter: "Centre de Notifications",
    notificationSubtitle: "Suivez l'activité et les inscriptions de la communauté",
    markAllAsRead: "Tout marquer comme lu",
    newAlert: "Nouvelle alerte",
    noNotifications: "Aucune notification trouvée",
    toastLoadNotifFailed: "Échec du chargement des notifications.",
    toastUpdateNotifFailed: "Échec de la mise à jour du statut de la notification.",
    toastAllMarkedRead: "Toutes les notifications ont été marquées comme lues.",
    toastMarkAllFailed: "Échec de la mise à jour des notifications.",
    toastNotifDeleted: "Notification supprimée.",
    toastDeleteNotifFailed: "Échec de la suppression de la notification.",
    activeMissionsSub: "missions locales actives",
    pointsManagedSub: "points de collecte gérés",
    communityUpdatesSub: "Mises à jour et messages de la communauté",
    configureProfileSub: "Configurez le logo, la bannière et le profil de l'entreprise",
    noNotifs: "Aucune notification",
    pointName: "Nom du Point",
    coordinates: "Coordonnées",
    depositMap: "Carte des Points de Dépôt",
    noPointsYet: "Aucun point de collecte configuré pour le moment.",
    searchPlaceholderPoints: "Rechercher par nom ou adresse...",
    streetAddress: "Adresse",
    pointPhoto: "Photo de l'Emplacement",
    uploadImage: "Téléverser une Image",
    createPoint: "Créer le Point",
    pointDetails: "Détails du Point",
    closeDetails: "Fermer les Détails",
    confirmDeletePointMsg: "Voulez-vous vraiment supprimer ce point ? Les utilisateurs ne le verront plus sur la carte.",
    upcomingLabel: "À Venir",
    completedLabel: "Terminé",
    activeLabel: "Actif",
    pointsRequiredLabel: "Points Requis",
    durationLabel: "Durée",
    registrationsLabel: "Participantes",
    filterStatusLabel: "Filtrer par Statut",
    searchPlaceholderMissions: "Rechercher par nom de mission ou catégorie...",
    emptyMissionsList: "Aucune mission locale créée pour le moment.",
    noRegistrationsYet: "Aucun participant pour cette mission pour le moment.",
    createMissionBtn: "Créer une Mission Locale",
    editMissionBtn: "Modifier la Mission Locale",
    deleteMissionBtn: "Supprimer la Mission Locale",
    confirmDelete: "Supprimer",
    titlePlaceholder: "ex. Aider à planter des arbres urbains",
    categoryPlaceholder: "ex. Plantation, Nettoyage",
    pointsPlaceholder: "ex. 50",
    uploadPhoto: "Téléverser une Photo",
    changePhoto: "Changer de Photo",
    pointsGrantedLabel: "Points Attribués",
    analytics: "Analytique",
    supportMessages: "Messages de support",
    faq: "FAQ",
    supportProofs: "Preuves de Soutien",
    pendingValidationDon: "Validations en attente",
    validatedThisMonth: "Validés ce mois-ci",
    refused: "Refusés",
    ptsGranted: "Points Accordés",
    vsLastMonth: "vs mois dernier",
    toValidate: "à valider",
    depositsThisMonth: "Dépôts ce mois-ci",
    refusalReasons: "Motifs de refus",
    categoryTrend: "Analytiques",
    myDepositLocations: "Mes Lieux de Dépôt",
    noActivePointSelected: "Aucun point actif sélectionné",
    ptsRequired: "pts requis",
    mission: "Mission",
    myOrganization: "Mon Organisation",
    enter: "Entrer",
    visualPreview: "Aperçu Visuel",
    newRecord: "Nouvel Enregistrement",
    searchLocationPlaceholder: "Rechercher l'emplacement...",
    findBtn: "Trouver",
    mapLocation: "Emplacement sur la carte",
    locationDetails: "Détails de l'emplacement",
    clickToPin: "CLIQUEZ POUR ÉPINGLER",
    points: "Points de Récompense",
    toastMissionCreated: "Mission locale créée avec succès.",
    toastMissionUpdated: "Mission locale mise à jour avec succès.",
    toastMissionSaveFailed: "Échec de l'enregistrement de la mission locale.",
    toastMissionDeleted: "Mission locale supprimée avec succès.",
    toastMissionDeleteFailed: "Échec de la suppression de la mission locale.",
    toastApproveSuccess: "Inscription du participant approuvée !",
    toastApproveFailed: "Échec de l'approbation du participant.",
    toastLoadMissionsFailed: "Échec du chargement des missions.",
    toastLoadParticipantsFailed: "Échec du chargement de la liste des participants.",
    toastLoadPointsFailed: "Échec du chargement des points de collecte.",
    toastPointCreated: "Point de collecte créé avec succès.",
    toastPointUpdated: "Point de collecte mis à jour avec succès.",
    toastPointSaveFailed: "Échec de l'enregistrement du point de collecte.",
    toastPointDeleted: "Point de collecte supprimé avec succès.",
    toastPointDeleteFailed: "Échec de la suppression du point de collecte.",
    approveBtn: "Valider",
    rejectBtn: "Refuser",
    approved: "Validé",
    rejected: "Refusé",
    toastRejectSuccess: "Participant refusé avec succès.",
    toastRejectFailed: "Échec du refus du participant.",
    food: "Nourriture",
    litter: "Litière",
    toys: "Jouets",
    medicine: "Médicaments",
    other: "Autre",
    blurredPhoto: "Photo Floue",
    itemNotVisible: "Article Non Visible",
    pointNotRecognized: "Point Non Reconnu",
    janShort: "JAN",
    febShort: "FÉV",
    marShort: "MAR",
    aprShort: "AVR",
    mayShort: "MAI",
    junShort: "JUIN",
    julShort: "JUIL",
    augShort: "AOÛT",
    sepShort: "SEP",
    octShort: "OCT",
    novShort: "NOV",
    decShort: "DÉC",
    sunShort: "DIM",
    monShort: "LUN",
    tueShort: "MAR",
    wedShort: "MER",
    thuShort: "JEU",
    friShort: "VEN",
    satShort: "SAM",
    weekly: "Hebdomadaire",
    monthly: "Mensuel",
    yearly: "Annuel",
    lifetime: "À vie",
    noDataFound: "AUCUNE DONNÉE TROUVÉE.",
    exportBtn: "Exporter",
    hestekaPartner: "Partenaire HESTEKA",
    supportVia: "Soutien Via",
    quantityLabel: "Quantité",
    association: "Association",
    dateLabel: "DATE",
    statusLabel: "STATUT",
    actionsLabel: "ACTIONS",
    viewImage: "Voir l'image",
    allStatuses: "TOUS",
    pending: "EN ATTENTE",
    loadingLabel: "CHARGEMENT...",
    supportProofsSub: "Examiner et valider les dons physiques",
    analyticsSub: "Suivez la croissance de votre écosystème",
    supportMessagesSub: "Contactez notre équipe de support",
    faqSub: "Foire aux questions",
    participationsMonth: "Participants par mois",
    missionsTitle: "Missions Locales",
    collectionPointsTitle: "Points de Collecte",
    newParticipantTitle: "Nouveau participant !",
    faqTitle: "Foire aux questions",
    faqSubtitle: "Trouvez des réponses aux questions courantes sur la gestion de vos points de collecte, de vos missions locales et de votre compte partenaire.",
    noFaqsFound: "Aucune FAQ trouvée pour le moment.",
    nameField: "Nom",
    emailField: "Email",
    newTicket: "Nouveau Ticket",
    subjectLabel: "SUJET",
    subject: "Sujet",
    message: "Message",
    noMessagesFound: "VOUS N'AVEZ ENVOYÉ AUCUN MESSAGE DE SUPPORT.",
    messageSentSuccess: "Message envoyé avec succès ! Nous vous contacterons bientôt.",
    messageSentFailed: "Échec de l'envoi du message",
    view: "Voir",
    ticketDetails: "Détails du Ticket",
    yourMessage: "Votre Message",
    adminReply: "Réponse de l'Admin",
    close: "Fermer",
    searchPlaceholder: "Rechercher...",
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("partnerLang") || "en");

  const handleSetLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem("partnerLang", newLang);
  };

  const t = translations[lang];

  const formatNotification = (title, description) => {
    let newTitle = title;

    if (title === "New Participant!" || title === "Nouveau participant !") {
      newTitle = t.newParticipantTitle || (lang === 'fr' ? "Nouveau participant !" : "New Participant!");
    } else if (title === "Points reçus !") {
      newTitle = lang === 'fr' ? "Points reçus !" : "Points received!";
    } else if (title === "Registration Registered" || title === "Inscription enregistrée") {
      newTitle = lang === 'fr' ? "Inscription enregistrée" : "Registration Registered";
    } else if (title === "Mission not approved" || title === "Mission non validée") {
      newTitle = lang === 'fr' ? "Mission non validée" : "Mission not approved";
    } else if (title === "Points gagnés !") {
      newTitle = lang === 'fr' ? "Points gagnés !" : "Points earned!";
    } else if (title === "Soutien approuvé !") {
      newTitle = lang === 'fr' ? "Soutien approuvé !" : "Support approved!";
    } else if (title === "Points approuvés !") {
      newTitle = lang === 'fr' ? "Points approuvés !" : "Points approved!";
    }

    // 1. New Participant
    const participantEnMatch = description?.match(/The user "(.*?)" has registered for your mission "(.*?)"\./);
    const participantFrMatch = description?.match(/L'utilisateur "(.*?)" s'est inscrit à votre mission "(.*?)"\./);
    const participantMatch = participantEnMatch || participantFrMatch;
    
    if (participantMatch) {
      return {
        title: newTitle,
        description: lang === 'fr'
          ? `L'utilisateur "${participantMatch[1]}" s'est inscrit à votre mission "${participantMatch[2]}".`
          : `The user "${participantMatch[1]}" has registered for your mission "${participantMatch[2]}".`
      };
    }

    // 2. Custom points
    const customPointsMatch = description?.match(/Vous avez reçu (\d+) points de la part de l'administrateur\./);
    if (customPointsMatch) {
      return {
        title: newTitle,
        description: lang === 'fr'
          ? `Vous avez reçu ${customPointsMatch[1]} points de la part de l'administrateur.`
          : `You received ${customPointsMatch[1]} points from the administrator.`
      };
    }

    // 3. Registration successful
    const regEnMatch = description?.match(/Your registration for the mission "(.*?)" has been successfully registered\./);
    const regFrMatch = description?.match(/Votre inscription à la mission "(.*?)" a été enregistrée avec succès\./);
    const regMatch = regEnMatch || regFrMatch;
    if (regMatch) {
      return {
        title: newTitle,
        description: lang === 'fr'
          ? `Votre inscription à la mission "${regMatch[1]}" a été enregistrée avec succès.`
          : `Your registration for the mission "${regMatch[1]}" has been successfully registered.`
      };
    }

    // 4. Mission rejected
    const rejEnMatch = description?.match(/Your participation in the mission "(.*?)" was not approved\./);
    const rejFrMatch = description?.match(/Votre participation à la mission "(.*?)" n'a pas été validée\./);
    const rejMatch = rejEnMatch || rejFrMatch;
    if (rejMatch) {
      return {
        title: newTitle,
        description: lang === 'fr'
          ? `Votre participation à la mission "${rejMatch[1]}" n'a pas été validée.`
          : `Your participation in the mission "${rejMatch[1]}" was not approved.`
      };
    }

    // 5. Points earned for mission
    const missionPtsMatch = description?.match(/Félicitations ! Vous avez gagné (\d+) points pour votre participation à la mission "(.*?)"\./);
    if (missionPtsMatch) {
      return {
        title: newTitle,
        description: lang === 'fr'
          ? `Félicitations ! Vous avez gagné ${missionPtsMatch[1]} points pour votre participation à la mission "${missionPtsMatch[2]}".`
          : `Congratulations! You earned ${missionPtsMatch[1]} points for your participation in the mission "${missionPtsMatch[2]}".`
      };
    }

    // 6. Support proof approved (grouped or single)
    const proofMatch = description?.match(/Votre preuve de soutien de (\d+) a été approuvée(?:\s*par validation groupée)?\. Vous avez gagné (\d+) points\./);
    if (proofMatch) {
      const isGrouped = description.includes("par validation groupée");
      return {
        title: newTitle,
        description: lang === 'fr'
          ? `Votre preuve de soutien de ${proofMatch[1]} a été approuvée${isGrouped ? " par validation groupée" : ""}. Vous avez gagné ${proofMatch[2]} points.`
          : `Your support proof of ${proofMatch[1]} was approved${isGrouped ? " by bulk validation" : ""}. You earned ${proofMatch[2]} points.`
      };
    }

    // 7. Report points
    const reportPtsMatch = description?.match(/Félicitations ! Vous avez gagné (\d+) points pour votre signalement "(.*?)"\./);
    if (reportPtsMatch) {
      return {
        title: newTitle,
        description: lang === 'fr'
          ? `Félicitations ! Vous avez gagné ${reportPtsMatch[1]} points pour votre signalement "${reportPtsMatch[2]}".`
          : `Congratulations! You earned ${reportPtsMatch[1]} points for your report "${reportPtsMatch[2]}".`
      };
    }

    return { title: newTitle, description: description };
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t, formatNotification }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
